const Data = [
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Raze",
        img: require("../../assets/raze/raze.png"),
        role: "Duelist",
        A1: "INSTANTLY throw a Blast Pack that will stick to surfaces. RE-USE the ability after deployment to detonate, damaging and moving anything hit. Raze isn't damaged by this ability, but will still take fall damage if launched up far enough.",
        A2: "EQUIP a cluster grenade. FIRE to throw the grenade, which does damage and creates sub-munitions, each doing damage to anyone in their range.",
        A3: "EQUIP a Boom Bot. FIRE will deploy the bot, causing it to travel in a straight line on the ground, bouncing off walls. The Boom Bot will lock on to any enemies in its frontal cone and chase them, exploding for heavy damage if it reaches them.",
        A4: "EQUIP a rocket launcher. FIRE shoots a rocket that does massive area damage on contact with anything.",
        A1_img: require("../../assets/raze/blast-pack.svg"),
        A2_img: require("../../assets/raze/paint-shells.svg"),
        A3_img: require("../../assets/raze/boom-bot.svg"),
        A4_img: require("../../assets/raze/showstopper.svg")
    },
    {
        name: "Brimstone",
        img: require("../../assets/brimstone/brimstone.png"),
        role: "Controller",
        A1: "EQUIP an incendiary grenade launcher. FIRE to launch a grenade that detonates as it comes to a rest on the floor, creating a lingering fire zone that damages players within the zone.",
        A2: "EQUIP a tactical map. FIRE to set locations where Brimstone’s smoke clouds will land. ALTERNATE FIRE to confirm, launching long-lasting smoke clouds that block vision in the selected area.",
        A3: "EQUIP a stim beacon. FIRE to toss the stim beacon in front of Brimstone. Upon landing, the stim beacon will create a field that grants players RapidFire.",
        A4: "EQUIP a tactical map. FIRE to launch a lingering orbital strike laser at the selected location, dealing high damage-over-time to players caught in the selected area.",
        A1_img: require("../../assets/brimstone/incendiary.svg"),
        A2_img: require("../../assets/brimstone/sky-smoke.svg"),
        A3_img: require("../../assets/brimstone/stim-beacon.svg"),
        A4_img: require("../../assets/brimstone/orbital-strike.svg")
    },
    {
        name: "Sage",
        img: require("../../assets/sage/sage.png"),
        role: "Sentinel",
        A1: "EQUIP a slowing orb. FIRE to throw a slowing orb forward that detonates upon landing, creating a lingering field that slows players caught inside of it.",
        A2: "EQUIP a healing orb. FIRE with your crosshairs over a damaged ally to activate a heal-over-time on them. ALT FIRE while Sage is damaged to activate a self heal-over-time.",
        A3: "EQUIP a barrier orb. FIRE places a solid wall. ALT FIRE rotates the targeter.",
        A4: "EQUIP a resurrection ability. FIRE with your crosshairs placed over a dead ally to begin resurrecting them. After a brief channel, the ally will be brought back to life with full health.",
        A1_img: require("../../assets/sage/slow-orb.svg"),
        A2_img: require("../../assets/sage/healing-orb.svg"),
        A3_img: require("../../assets/sage/barrier-orb.svg"),
        A4_img: require("../../assets/sage/resurrection.svg")
    },
    {
        name: "Omen",
        img: require("../../assets/omen/omen.png"),
        role: "Controller",
        A1: "INSTANTLY fire a shadow projectile forward, briefly reducing the vision range of all players it touches. This projectile can pass straight through walls.",
        A2: "EQUIP a shadow orb and see its range indicator. FIRE to throw the shadow orb to the marked location, creating a long-lasting shadow sphere that blocks vision. HOLD ALTERNATE FIRE while targeting to move the marker further away. HOLD the ability key with targeting to move the marker closer.",
        A3: "EQUIP a shadow walk ability and see its range indicator. FIRE to begin a brief channel, then teleport to the marked location.",
        A4: "EQUIP a tactical map. FIRE to begin teleporting to the selected location. While teleporting, Omen will appear as a Shade that can be destroyed by an enemy to cancel his teleport.",
        A1_img: require("../../assets/omen/paranoia.svg"),
        A2_img: require("../../assets/omen/dark-cover.svg"),
        A3_img: require("../../assets/omen/shrouded-step.svg"),
        A4_img: require("../../assets/omen/from-the-shadows.svg")
    },
    {
        name: "Cypher",
        img: require("../../assets/cypher/cypher.png"),
        role: "Sentinel",
        A1: "INSTANTLY toss the cyber cage in front of Cypher. Activate to create a zone that blocks vision and slows enemies who pass through it.",
        A2: "EQUIP a spycam. FIRE to place the spycam at the targeted location. RE-USE this ability to take control of the camera’s view. While in control of the camera, FIRE to shoot a marking dart. This dart will reveal the location of any player struck by the dart.",
        A3: "EQUIP a trapwire. FIRE to place a destructible and covert tripwire at the targeted location creating a line that spans between the placed location and the wall opposite. Enemy players who cross a tripwire will be tethered, revealed, and dazed after a short period if they do not destroy the device in time. This ability can be picked up to be REDEPLOYED.",
        A4: "INSTANTLY use on a dead enemy player in your crosshairs to reveal the location of all living enemy players.",
        A1_img: require("../../assets/cypher/cyber-cage.svg"),
        A2_img: require("../../assets/cypher/spycam.svg"),
        A3_img: require("../../assets/cypher/trapwire.svg"),
        A4_img: require("../../assets/cypher/neural-theft.svg")
    },
    {
        name: "Phoenix",
        img: require("../../assets/phoenix/phoenix.png"),
        role: "Duelist",
        A1: "EQUIP a flare orb that takes a curving path and detonates shortly after throwing. FIRE to curve the flare orb to the left, detonating and blinding any player who sees the orb. ALTERNATE FIRE to curve the flare orb to the right.",
        A2: "EQUIP a fireball. FIRE to throw a fireball that explodes after a set amount of time or upon hitting the ground, creating a lingering fire zone that damages enemies.",
        A3: "EQUIP a flame wall. FIRE to create a line of flame that moves forward, creating a wall of fire that blocks vision and damages players passing through it. HOLD FIRE to bend the wall in the direction of your crosshair.",
        A4: "INSTANTLY place a marker at Phoenix’s location. While this ability is active, dying or allowing the timer to expire will end this ability and bring Phoenix back to this location with full health.",
        A1_img: require("../../assets/phoenix/curveball.svg"),
        A2_img: require("../../assets/phoenix/hot-hands.svg"),
        A3_img: require("../../assets/phoenix/blaze.svg"),
        A4_img: require("../../assets/phoenix/run-it-back.svg")
    },
    {
        name: "Viper",
        img: require("../../assets/viper/viper.png"),
        role: "Controller",
        A1: "EQUIP a gas emitter. FIRE to throw the emitter that perpetually remains throughout the round. RE-USE the ability to create a toxic gas cloud at the cost of fuel. This ability can be RE-USED more than once and can be picked up to be REDEPLOYED.",
        A2: "EQUIP a gas emitter launcher. FIRE to deploy a long line of gas emitters. RE-USE the ability to create a tall wall of toxic gas at the cost of fuel. This ability can be RE-USED more than once.",
        A3: "EQUIP a chemical launcher. FIRE to launch a canister that shatters upon hitting the floor, creating a lingering chemical zone that damages and slows enemies.",
        A4: "EQUIP a chemical sprayer. FIRE to spray a chemical cloud in all directions around Viper, creating a large cloud that reduces the vision range and maximum health of players inside of it.",
        A1_img: require("../../assets/viper/poison-cloud.svg"),
        A2_img: require("../../assets/viper/toxic-screen.svg"),
        A3_img: require("../../assets/viper/snake-bite.svg"),
        A4_img: require("../../assets/viper/vipers-pit.svg")
    },
    {
        name: "Sova",
        img: require("../../assets/sova/sova.png"),
        role: "Initiator",
        A1: "EQUIP a bow with a shock bolt. FIRE to send the explosive forward, detonating upon collision and damaging players nearby. HOLD FIRE to extend the range of the projectile. ALTERNATE FIRE to add up to two bounces to this arrow.",
        A2: "EQUIP a bow with a recon bolt. FIRE to send the recon bolt forward, activating upon collision and revealing the location of nearby enemies caught in the line of sight of the bolt. HOLD FIRE to extend the range of the projectile. ALTERNATE FIRE to add up to two bounces to this arrow.",
        A3: "EQUIP an owl drone. FIRE to deploy and take control of movement of the drone. While in control of the drone, FIRE to shoot a marking dart. This dart will reveal the location of any player struck by the dart.",
        A4: "EQUIP a bow with three long-range wall-piercing energy blasts. FIRE to release an energy blast in a line in front of Sova, dealing damage and revealing the location of enemies caught in the line. This ability can be RE-USED up to two more times while the ability timer is active.",
        A1_img: require("../../assets/sova/hunters-fury.svg"),
        A2_img: require("../../assets/sova/owl-drone.svg"),
        A3_img: require("../../assets/sova/recon-bolt.svg"),
        A4_img: require("../../assets/sova/shock-bolt.svg")
    },
    {
        name: "Breach",
        img: require("../../assets/breach/breach.png"),
        role: "Initiator",
        A1: "EQUIP a blinding charge. FIRE the charge to set fast-acting burst through the wall. The charge detonates to blind all players looking at it.",
        A2: "EQUIP a seismic blast. HOLD FIRE to increase the distance. RELEASE to set off the quake, dazing all players in its zone and in a line up to the zone.",
        A3: "EQUIP a fusion charge. FIRE the charge to set a slow-acting burst through the wall. The burst does heavy damage to anyone caught in its area.",
        A4: "EQUIP a seismic charge. FIRE to send a cascading quake through all terrain in a large cone. The quake dazes and knocks up anyone caught in it.",
        A1_img: require("../../assets/breach/rolling-thunder.svg"),
        A2_img: require("../../assets/breach/aftershock.svg"),
        A3_img: require("../../assets/breach/fault-line.svg"),
        A4_img: require("../../assets/breach/flashpoint.svg")
    }
];
  
export default Data;
