const Data = [
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    },
    {
        name: "Jett",
        img: require("../../assets/jett/jett.png"),
        role: "Duelist",
        A1: "EQUIP a set of highly accurate knives that recharge on killing an opponent. FIRE to throw a single knife at your target. ALTERNATE FIRE to throw all remaining daggers at your target.",
        A2: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
        A3: "INSTANTLY propel Jett high into the air.",
        A4: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward.",
        A1_img: require("../../assets/jett/blade-storm.svg"),
        A2_img: require("../../assets/jett/cloudburst.svg"),
        A3_img: require("../../assets/jett/updraft.svg"),
        A4_img: require("../../assets/jett/tailwind.svg")
    }
];
  
export default Data;
